export const CREATE_MENU_ITEM_REQUEST = "CREATE_MENU_ITEM_REQUEST";
export const CREATE_MENU_ITEM_SUCCESS = "CREATE_MENU_ITEM_SUCCESS";
export const CREATE_MENU_ITEM_FAILURE = "CREATE_MENU_ITEM_FAILURE";

export const GET_MENU_ITEMS_BY_RESTAURANT_ID_REQUEST =
  "GET_MENU_ITEMS_BY_RESTAURANT_ID_REQUEST";
export const GET_MENU_ITEMS_BY_RESTAURANT_ID_SUCCESS =
  "GET_MENU_ITEMS_BY_RESTAURANT_ID_SUCCESS";
export const GET_MENU_ITEMS_BY_RESTAURANT_ID_FAILURE =
  "GET_MENU_ITEMS_BY_RESTAURANT_ID_FAILURE";

export const DELETE_MENU_ITEM_REQUEST = "DELETE_MENU_ITEM_REQUEST";
export const DELETE_MENU_ITEM_SUCCESS = "DELETE_MENU_ITEM_SUCCESS";
export const DELETE_MENU_ITEM_FAILURE = "DELETE_MENU_ITEM_FAILURE";

export const SEARCH_MENU_ITEM_REQUEST = "UPDATE_MENU_ITEM_REQUEST";
export const SEARCH_MENU_ITEM_SUCCESS = "UPDATE_MENU_ITEM_SUCCESS";
export const SEARCH_MENU_ITEM_FAILURE = "UPDATE_MENU_ITEM_FAILURE";

export const UPDATE_MENU_ITEM_AVAILBILITY_REQUEST =
  "UPDATE_MENU_ITEM_AVAILBILITY_REQUEST";
export const UPDATE_MENU_ITEM_AVAILBILITY_SUCCESS =
  "UPDATE_MENU_ITEM_AVAILBILITY_SUCCESS";
export const UPDATE_MENU_ITEM_AVAILBILITY_FAILURE =
  "UPDATE_MENU_ITEM_AVAILBILITY_FAILURE";

// Update category for existing food item
export const UPDATE_MENU_ITEM_CATEGORY_REQUEST = "UPDATE_MENU_ITEM_CATEGORY_REQUEST";
export const UPDATE_MENU_ITEM_CATEGORY_SUCCESS = "UPDATE_MENU_ITEM_CATEGORY_SUCCESS";
export const UPDATE_MENU_ITEM_CATEGORY_FAILURE = "UPDATE_MENU_ITEM_CATEGORY_FAILURE";
